# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - release
  - devel

sudo: required
cache: packages
env:
  global:
    google_api_key: $google_api_key
    mapbox_api_key: $mapbox_api_key
    nomis_api_key: $nomis_api_key

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ppa --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev

after_success:
  - Rscript -e 'covr::codecov(quiet=FALSE)'
